// Generated by scripts/sync-items.mjs
// Date: 2026-02-07T12:29:19.593Z

export interface ItemRecord {
  id: string;
  name: string;
  slug: string;
  category: string;
  type?: string;
  flavorText?: string;
  description?: string;
  
  armor?: number;
  attack?: number;
  defense?: number;
  weight?: number;
  imbuementSlots?: number;
  levelRequired?: number;
  vocation?: string;
  
  value?: string;
  npcValue?: number;
  buyFrom?: string;
  sellTo?: string;
  
  droppedBy?: string[];

  implemented?: string;
  
  image?: string | null;
}

export const itemsDb: ItemRecord[] = [
  {
    "id": "200-theons",
    "name": "200 Theons",
    "slug": "200-theons",
    "category": "Quest Items",
    "type": "Quest Items",
    "description": "''Theons'' are a special currency related to [[Tibia's 25th Anniversary]].",
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [
      "Retros Treasure"
    ],
    "implemented": "12.85.11485",
    "image": null
  },
  {
    "id": "25-years-backpack",
    "name": "25 Years Backpack",
    "slug": "25-years-backpack",
    "category": "Containers",
    "type": "Containers",
    "flavorText": "It could be bought for Theons after the festivities of Tibia's 25th anniversary.",
    "description": "See [[Backpacks]] for general information regarding backpacks.\n\nOne can be obtained by characters who received at least 7,197 [[Theons]] during [[Tibia's 25th Anniversary]] and open their open {{ilink|Big Reward Box}} [[Big Reward Box]].",
    "weight": 17,
    "imbuementSlots": 1,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "12.87.12038",
    "image": null
  },
  {
    "id": "50-theons",
    "name": "50 Theons",
    "slug": "50-theons",
    "category": "Quest Items",
    "type": "Quest Items",
    "description": "''Theons'' are a special currency related to [[Tibia's 25th Anniversary]].",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [
      "Great Timedisplaced Anomaly",
      "Major Timedisplaced Anomaly",
      "Major Timedisplaced Anomaly (Fiehonja)",
      "Minor Timedisplaced Anomaly",
      "Minor Timedisplaced Anomaly (Rookgaard)",
      "Timedisplaced Anomaly",
      "Major Timedisplaced Anomaly (Issavi)",
      "Major Timedisplaced Anomaly (Rascacoon)",
      "Minor Timedisplaced Anomaly (Ankrahmun)",
      "Minor Timedisplaced Anomaly (Greenshore)",
      "Timedisplaced Anomaly (Banuta)",
      "Timedisplaced Anomaly (Chazorai)",
      "Timedisplaced Anomaly (Warzone)"
    ],
    "implemented": "12.85.11485",
    "image": null
  },
  {
    "id": "7197-theons",
    "name": "7197 Theons",
    "slug": "7197-theons",
    "category": "Quest Items",
    "type": "Quest Items",
    "description": "''Theons'' are a special currency related to [[Tibia's 25th Anniversary]]. \n\nYou obtain this once you defeat [[Lord Retro]] ([[Retros Treasure]]) for the first time during the [[Tibia's 25th Anniversary]].\n\nThe number resembles \"7th January 1997\", the date [[Tibia]] was released.",
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [
      "Retros Treasure"
    ],
    "implemented": "12.85.11485",
    "image": null
  },
  {
    "id": "abacus",
    "name": "Abacus",
    "slug": "abacus",
    "category": "Fansite Items",
    "type": "Fansite Items",
    "flavorText": "If you use it wisely, you may write yourself into the history books. It was awarded by Erig.",
    "description": "You can only read the text if you stand 2 SQMs from it or closer.\nErig owns 2 abaci, with the text:\n*{{Message|type=look|If you possess this abacus, you are a thief. Please return it to Erig at once!}}\n*{{Message|type=look|Last Abacus, created in memory of erig.net, supported fansite of Tibia till March 2009.}}\nThis item can no longer be obtained due to the closure of [[Erig.net]] on March 28, 2009.\n\nIts replica is the [[Abacus (Replica)]].\n\n<noinclude><p><gallery mode=\"nolines\">\nAbacuserig21.png|One of the abaci\n</gallery></p></noinclude>",
    "weight": 12,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "7.8",
    "image": null
  },
  {
    "id": "abacus-replica",
    "name": "Abacus (Replica)",
    "slug": "abacus-replica",
    "category": "Valuables",
    "type": "Valuables",
    "flavorText": "Souvenir from Thais Museum.",
    "description": "You can obtain this item by trading 20 [[Silver Raid Token]]s to [[Jorge]]. This is a replica of a [[Abacus]].",
    "weight": 12,
    "npcValue": 0,
    "buyFrom": "Jorge",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "10.10",
    "image": "/items/abacus-replica.gif"
  },
  {
    "id": "abominations-eye",
    "name": "Abomination's Eye",
    "slug": "abominations-eye",
    "category": "Creature Products",
    "type": "Creature Products",
    "description": "{{CreatureProductNotes}}",
    "weight": 0.5,
    "value": "Negotiable",
    "npcValue": 650000,
    "buyFrom": "--",
    "sellTo": "Yasir",
    "droppedBy": [
      "The Abomination"
    ],
    "implemented": "12.70.10953",
    "image": "/items/abominations-eye.gif"
  },
  {
    "id": "abominations-tail",
    "name": "Abomination's Tail",
    "slug": "abominations-tail",
    "category": "Creature Products",
    "type": "Creature Products",
    "description": "{{CreatureProductNotes}}",
    "weight": 0.8,
    "value": "Negotiable",
    "npcValue": 700000,
    "buyFrom": "--",
    "sellTo": "Yasir",
    "droppedBy": [
      "The Abomination"
    ],
    "implemented": "12.70.10953",
    "image": "/items/abominations-tail.gif"
  },
  {
    "id": "abominations-tongue",
    "name": "Abomination's Tongue",
    "slug": "abominations-tongue",
    "category": "Creature Products",
    "type": "Creature Products",
    "description": "{{CreatureProductNotes}}",
    "weight": 1.3,
    "value": "Negotiable",
    "npcValue": 950000,
    "buyFrom": "--",
    "sellTo": "Yasir",
    "droppedBy": [
      "The Abomination"
    ],
    "implemented": "12.70.10953",
    "image": "/items/abominations-tongue.gif"
  },
  {
    "id": "abridged-promotion-scroll",
    "name": "Abridged Promotion Scroll",
    "slug": "abridged-promotion-scroll",
    "category": "Valuables",
    "type": "Valuables",
    "flavorText": "Only a hero of level 51 or above can decipher this scroll to gain 3 promotion points for the Wheel of Destiny.",
    "description": "Using this [[Promotion Scroll]] produces the server message \"{{Server Message|You have successfully used the item and received bonus promotion points.}}\" and grants the character 3 promotion points to spend in the [[Wheel of Destiny]]. Each character can only use it once. Can only be dropped from [[Bakragore]] when fighting it under the influence of its [[Bakragore's Taints|final taint]].",
    "weight": 1.2,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [
      "Bakragore"
    ],
    "implemented": "13.20.13560",
    "image": "/items/abridged-promotion-scroll.gif"
  },
  {
    "id": "abyss-hammer",
    "name": "Abyss Hammer",
    "slug": "abyss-hammer",
    "category": "Club Weapons",
    "type": "Club Weapons",
    "flavorText": "Floating stones form the tip of this strange weapon, held in place by unspeakable magic.",
    "description": "This mysterious hammer is a very rare item since it can only be obtained in places hard to reach, such as some parts of [[The Inquisition Quest]] or deep in the [[Pits of Inferno]].",
    "attack": 47,
    "defense": 21,
    "weight": 55,
    "imbuementSlots": 3,
    "levelRequired": 60,
    "vocation": "knights",
    "value": "Negotiable",
    "npcValue": 20000,
    "buyFrom": "--",
    "sellTo": "Rashid",
    "droppedBy": [
      "Alptramun",
      "Ferumbras",
      "Ferumbras Mortal Shell",
      "Grimeleech",
      "Hand of Cursed Fate",
      "Izcandar the Banished",
      "King Zelos",
      "Lady Tenebris",
      "Malofur Mangrinder",
      "Maxxenius",
      "Phantasm",
      "Plagueroot",
      "Prince Drazzak",
      "Renegade Quara Predator",
      "The Nightmare Beast",
      "The Percht Queen",
      "The Scourge of Oblivion",
      "The Shatterer"
    ],
    "implemented": "8.00",
    "image": "/items/abyss-hammer.gif"
  },
  {
    "id": "abyssadors-lash",
    "name": "Abyssador's Lash",
    "slug": "abyssadors-lash",
    "category": "Quest Items",
    "type": "Quest Items",
    "description": "A creature product which can be given to [[Gnomission]] by saying ''hero''. Once handed in you will no longer need a [[Red Teleport Crystal]] to enter the third warzone, meaning you can hunt there but cannot fight [[Abyssador]] more than once in a 20 hour period.",
    "weight": 1.9,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [
      "Abyssador"
    ],
    "implemented": "9.60",
    "image": "/items/abyssadors-lash.gif"
  },
  {
    "id": "abyssal-calamary-soul-core",
    "name": "Abyssal Calamary Soul Core",
    "slug": "abyssal-calamary-soul-core",
    "category": "Soul Cores",
    "type": "Soul Cores",
    "flavorText": "Offers a soul to the Soulpit. Combine with another soul core to create a random new soul core.",
    "weight": 10,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "13.40.54ea79",
    "image": "/items/abyssal-calamary-soul-core.gif"
  },
  {
    "id": "acid-blob-soul-core",
    "name": "Acid Blob Soul Core",
    "slug": "acid-blob-soul-core",
    "category": "Soul Cores",
    "type": "Soul Cores",
    "flavorText": "Offers a soul to the Soulpit. Combine with another soul core to create a random new soul core.",
    "weight": 10,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "13.40.54ea79",
    "image": "/items/acid-blob-soul-core.gif"
  },
  {
    "id": "acid-resistant-fishing-rod",
    "name": "Acid Resistant Fishing Rod",
    "slug": "acid-resistant-fishing-rod",
    "category": "Quest Items",
    "type": "Quest Items",
    "description": "Part of [[The Dream Courts Quest]].",
    "weight": 8.5,
    "value": "?",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "12.00.7695",
    "image": "/items/acid-resistant-fishing-rod.gif"
  },
  {
    "id": "acolyte-of-darkness-soul-core",
    "name": "Acolyte of Darkness Soul Core",
    "slug": "acolyte-of-darkness-soul-core",
    "category": "Soul Cores",
    "type": "Soul Cores",
    "flavorText": "Offers a soul to the Soulpit. Combine with another soul core to create a random new soul core.",
    "weight": 10,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "13.40.54ea79",
    "image": "/items/acolyte-of-darkness-soul-core.gif"
  },
  {
    "id": "acolyte-of-the-cult-soul-core",
    "name": "Acolyte of the Cult Soul Core",
    "slug": "acolyte-of-the-cult-soul-core",
    "category": "Soul Cores",
    "type": "Soul Cores",
    "flavorText": "Offers a soul to the Soulpit. Combine with another soul core to create a random new soul core.",
    "weight": 10,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "13.40.54ea79",
    "image": "/items/acolyte-of-the-cult-soul-core.gif"
  },
  {
    "id": "acorn",
    "name": "Acorn",
    "slug": "acorn",
    "category": "Creature Products",
    "type": "Creature Products",
    "description": "A creature product. It can be sold to NPCs, and as with other creature products, has among the highest gold-to-oz ratio of all items. <br>50 Are needed in [[Forgotten Knowledge Quest]].<br/>",
    "weight": 0.5,
    "value": "Negotiable",
    "npcValue": 10,
    "buyFrom": "--",
    "sellTo": "A Fluffy Squirrel, Inigo, Yasir",
    "droppedBy": [
      "Badger",
      "Squirrel"
    ],
    "implemented": "8.54",
    "image": "/items/acorn.gif"
  },
  {
    "id": "active-probing-device",
    "name": "Active Probing Device",
    "slug": "active-probing-device",
    "category": "Quest Items",
    "type": "Quest Items",
    "flavorText": "This thing looks highly instable, you better find a place to deploy it soon.",
    "description": "It looks the same as a [[Strange Probing Device (Instable)]] and a [[Strange Probing Device]].\nTemporarily obtained in the [[Oramond Quest]].",
    "weight": 8,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "10.50",
    "image": "/items/active-probing-device.gif"
  },
  {
    "id": "adamant-shield",
    "name": "Adamant Shield",
    "slug": "adamant-shield",
    "category": "Shields",
    "type": "Shields",
    "flavorText": "It was forged with magical diamonds collected during the journey of a true tibian. Awarded by TibiaLife.com.br",
    "description": "It's [[TibiaLife]]'s fansite item. When used, its color and light changes from Blue {{Color Box|{{RGB Light Color|23}}}} to Purple {{Color Box|{{RGB Light Color|154}}}} (and vice versa), as shown below, and it stays in the other color. It will also display one of its sounds.\n\n[[File:Adamant Shield 2.gif]]\n[[File:Adamant Shield 3.gif]]\n[[File:Adamant Shield 4.gif]]\n\nKnown receivers of this item: \n\n*{{character|Makadamia}}, item creator.\n*{{character|Carol Witt}}, administrator of [[TibiaLife]].\n\nThis item was {{OfficialNewsArchive|6663|awarded}} to four players during the [[Fansite Appreciation Day 2022]]. The winners were:\n* {{Character|Sir Demoleide}} ([[Solidera]])\n* {{Character|Snaidell}} ([[Nefera]])\n* {{Character|Luiz Faixas}} ([[Havera]])\n* {{Character|Duchess Lara}} ([[Nefera]])",
    "defense": 0,
    "weight": 91,
    "value": "Negotiable",
    "npcValue": 0,
    "buyFrom": "--",
    "sellTo": "--",
    "droppedBy": [],
    "implemented": "11.90.7293",
    "image": "/items/adamant-shield.gif"
  }
];

export const itemsBySlug: Record<string, ItemRecord> = Object.fromEntries(
  itemsDb.map((item) => [item.slug, item])
);
