// Generated by scripts/sync-npcs.mjs
// Date: 2026-02-07T12:42:57.373Z

export interface NPCService {
  name: string;
  type: "buy" | "sell" | "quest" | "travel" | "deposit" | "withdraw" | "heal" | "blessing" | "other";
  items?: string[];
  notes?: string;
}

export interface NPC {
  id: string;
  name: string;
  location: string;
  position: { x: number; y: number; z: number };
  town: string;
  services: NPCService[];
  description: string;
  image?: string;
  notes?: string;
}

export const npcs: NPC[] = [
  {
    "id": "npc-a-bearded-woman",
    "name": "A Bearded Woman",
    "location": "East of [[Northport]], in [[The Cave]]",
    "position": {
      "x": 127.82,
      "y": 123.127,
      "z": 10
    },
    "town": "Carlin",
    "services": [],
    "description": "Artist",
    "notes": "It is said that this [[NPC]] might be part of a [[Quest]] (see [[Talk:A Bearded Woman|talk]] for discussion). He pretended to be [[Princess Lumelia]] to do his pirate friend [[Captain Kid]] the favour of being acknowledged, but is in fact a man. After Captain Kid disappeared, however, the pirates in [[The Cave]] would not release him."
  },
  {
    "id": "npc-a-beautiful-girl",
    "name": "A Beautiful Girl",
    "location": "Inside [[Devovorga]]'s lair",
    "position": {
      "x": 128.168,
      "y": 123.28,
      "z": 10
    },
    "town": "Yalahar",
    "services": [],
    "description": "Informer",
    "notes": "This is [[Devovorga]]'s soul trapped in a human body.<br />\nPart of the [[Rise of Devovorga]] Quest, talk to her to awake [[Devovorga]]'s true form."
  },
  {
    "id": "npc-a-beggar",
    "name": "A Beggar",
    "location": "[[Lower Rathleton]], just west of the bridge to the [[Workshop Quarter]]",
    "position": {
      "x": 131.58,
      "y": 124.213,
      "z": 7
    },
    "town": "Rathleton",
    "services": [],
    "description": "Beggar",
    "notes": "Part of the [[Dark Trails Quest]]."
  },
  {
    "id": "npc-a-behemoth",
    "name": "A Behemoth",
    "location": "[[The Spike]] 8 levels down.",
    "position": {
      "x": 126.52,
      "y": 127.7,
      "z": 15
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Behemoth]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-bloodshade",
    "name": "A Bloodshade",
    "location": "Right at the entrance of the [[Blood Vestibule]].",
    "position": {
      "x": 128.188,
      "y": 126.142,
      "z": 9
    },
    "town": "Northern Darama",
    "services": [],
    "description": "NPC",
    "notes": "The [[NPC]] can explain the initial steps to enter the hunting grounds in the [[Blood Vestibule]], allowing players to proceed in the [[Rotten Blood Quest]]."
  },
  {
    "id": "npc-a-captive-forest-fury",
    "name": "A Captive Forest Fury",
    "location": "[[Corym Black Market]]",
    "position": {
      "x": 126.4,
      "y": 128.7,
      "z": 11
    },
    "town": "Liberty Bay",
    "services": [],
    "description": "Forest Fury",
    "notes": "Part of the [[Threatened Dreams Quest#Sweet Dreams|Threatened Dreams Quest - Sweet Dreams]]."
  },
  {
    "id": "npc-a-confused-frog",
    "name": "A Confused Frog",
    "location": "[[Eclesius]]' house, 2 floors down in a cell.",
    "position": {
      "x": 126.33,
      "y": 126.38,
      "z": 9
    },
    "town": "Thais",
    "services": [],
    "description": "Frog",
    "notes": "His name is (or was) [[Turian]]. He is involved in [[The Scatterbrained Sorcerer Quest]]."
  },
  {
    "id": "npc-a-dark-priestess",
    "name": "A Dark Priestess",
    "location": "Beneath the [[Demonwar Crypt]]",
    "position": {
      "x": 129.233,
      "y": 124.192,
      "z": 15
    },
    "town": "Edron",
    "services": [],
    "description": "Cleric",
    "notes": "She is a priestess of [[Zathroth]].\nPart of the [[Demon Wars World Change]]."
  },
  {
    "id": "npc-a-dead-bureaucrat",
    "name": "A Dead Bureaucrat",
    "location": "In the [[Pits of Inferno]], in a long hall.",
    "position": {
      "x": 127.217,
      "y": 126.37,
      "z": 15
    },
    "town": "Venore",
    "services": [],
    "description": "Servant",
    "notes": "There are actually four dead bureaucrats, but they all have the same name. They are minions of [[Pumin]], one of the [[The Ruthless Seven]].\nPart of the the [[Pits of Inferno Quest]]."
  },
  {
    "id": "npc-a-dragon-lord",
    "name": "A Dragon Lord",
    "location": "[[The Spike]] 7 levels down.",
    "position": {
      "x": 126.22,
      "y": 127.12,
      "z": 14
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Dragon Lord]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-dragon-mother",
    "name": "A Dragon Mother",
    "location": "[[Formorgar Mines]]",
    "position": {
      "x": 126.49,
      "y": 121.44,
      "z": 13
    },
    "town": "Svargrond",
    "services": [],
    "description": "Caretaker",
    "notes": "She takes good care of her eggs.Part of the [[Forgotten Knowledge Quest]]."
  },
  {
    "id": "npc-a-drillworm",
    "name": "A Drillworm",
    "location": "[[The Spike]] 6 floors down.",
    "position": {
      "x": 125.233,
      "y": 127.174,
      "z": 13
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Drillworm]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-dwarven-ghost",
    "name": "A Dwarven Ghost",
    "location": "[[Grothmok tunnels]] in the [[Dwarf Mines]].",
    "position": {
      "x": 126.151,
      "y": 124.174,
      "z": 12
    },
    "town": "Kazordoon",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "When alive his name was [[Shearton Softbeard]] and he was unbeatable at kissing. He died when the [[Grothmok tunnels]] caved in. The tunnels were then sealed off to stop others from dieing as well."
  },
  {
    "id": "npc-a-fading-memory",
    "name": "A Fading Memory",
    "location": "[[Vengoth]], high in the northern tower.",
    "position": {
      "x": 128.184,
      "y": 122.208,
      "z": 3
    },
    "town": "Farmine",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "Her real name is '''Kala''' and she used to be [[Arthei]]'s wife, as mentioned in [[Arthei's Descent into Vampirism I (Book)]]. Together with him and his brothers [[Marziel]], [[Lersatio]], and [[Boreth]], she left her hometown [[Carlin]] to search for a place that would make them feel at home. When after a curious incident her husband started acting cold and distant, she could not bear it and left the four brothers.She will give you a [[Ghost's Tear]] in the [[Blood Brothers Quest]]."
  },
  {
    "id": "npc-a-fluffy-squirrel",
    "name": "A Fluffy Squirrel",
    "location": "North-east of [[Carlin]]",
    "position": {
      "x": 126.156,
      "y": 123.24,
      "z": 7
    },
    "town": "Carlin",
    "services": [
      {
        "name": "Trade",
        "type": "other",
        "notes": "Buys/Sells (details not parsed yet)"
      }
    ],
    "description": "Collector",
    "notes": "This is the only [[NPC]] buying [[Walnut]]s."
  },
  {
    "id": "npc-a-frog",
    "name": "A Frog",
    "location": "[[Alatar Lake]], north of [[Thais]].",
    "position": {
      "x": 126.108,
      "y": 125.119,
      "z": 7
    },
    "town": "Thais",
    "services": [],
    "description": "Frog",
    "notes": "His name is '''Turian'''. He is involved in [[The Scatterbrained Sorcerer Quest]]."
  },
  {
    "id": "npc-a-ghostly-guardian",
    "name": "A Ghostly Guardian",
    "location": "In the [[Dream Realm]] under the [[Plains of Havoc]].",
    "position": {
      "x": 127.243,
      "y": 126.9,
      "z": 14
    },
    "town": "Venore",
    "services": [],
    "description": "Guard",
    "notes": "Tells some nice stories."
  },
  {
    "id": "npc-a-ghostly-knight",
    "name": "A Ghostly Knight",
    "location": "Leverroom in the [[Pits of Inferno]] under the [[Plains of Havoc]].",
    "position": {
      "x": 128.88,
      "y": 126.7,
      "z": 11
    },
    "town": "Venore",
    "services": [],
    "description": "Guard",
    "notes": "Tells some nice stories."
  },
  {
    "id": "npc-a-ghostly-sage",
    "name": "A Ghostly Sage",
    "location": "In the [[Pits of Inferno]] under the [[Plains of Havoc]].",
    "position": {
      "x": 128.6,
      "y": 125.245,
      "z": 10
    },
    "town": "Venore",
    "services": [],
    "description": "Sage",
    "notes": "This [[NPC]] is located at the end of the [[Pits of Inferno Quest]], just before you use [[Key 3700]] to access the reward room. He seems to be interested in trading something - something you usually wouldn't bring to the [[Pits of Inferno]].<br />\nHe wants [[God Flowers]]. After you give them to him he will give you a hint on how to get [[Key 3700]], which is needed to enter the reward room.<br />\nHe will teleport you out of the [[Pits of Inferno]]'s main room if you say \"teleport\" to him. You will arrive in the [[Slime]] cave under the [[Plains of Havoc]]."
  },
  {
    "id": "npc-a-ghostly-woman",
    "name": "A Ghostly Woman",
    "location": "[[Ghostlands]], two floors up",
    "position": {
      "x": 125.19,
      "y": 124.65,
      "z": 7
    },
    "town": "Carlin",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "This [[NPC]] is an unreachable illusion. She is actually located two levels above ground level, and when you approach her, she disappears (similar to the mirage in the desert near [[Darashia]]). On her left side there's an [[Axe]] with blood on it, and a dead human lying on the ground."
  },
  {
    "id": "npc-a-ghostly-woman-dream-realm",
    "name": "A Ghostly Woman (Dream Realm)",
    "location": "In the [[Dream Realm]] under the [[Plains of Havoc]].",
    "position": {
      "x": 128.67,
      "y": 126.33,
      "z": 14
    },
    "town": "Venore",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "She's a former [[Nightmare Knights|Nightmare Knight]]. She's cold and wants a pair of [[Boots]].\nPart of the [[Dreamer's Challenge Quest]]."
  },
  {
    "id": "npc-a-goblin-exile",
    "name": "A Goblin Exile",
    "location": "[[Krailos]], down a [[Pitfall]] to the east.",
    "position": {
      "x": 131.2,
      "y": 123.244,
      "z": 8
    },
    "town": "Krailos",
    "services": [],
    "description": "Clairvoyant",
    "notes": "He used to be a priest and now claims to be used as a conduit of the [[Frog God]] in order to save the goblins stuck on [[Krailos]]. He used to be called ''Nemmo Tokrok Argkaz Ar-Vanda Ho'Memot'', which roughly means ''The One Who Is No-One, Whose Name Is Buried in Memories of Days Lost Behind Closed Eyes''."
  },
  {
    "id": "npc-a-grumpy-cyclops",
    "name": "A Grumpy Cyclops",
    "location": "North-east of the harbour, in the [[Inner City]] in [[Yalahar]].",
    "position": {
      "x": 128.54,
      "y": 122.8,
      "z": 7
    },
    "town": "Yalahar",
    "services": [],
    "description": "Artisan",
    "notes": "He owns the weapons shop and makes the weapons, while [[Morpel]] just sells the weapons and talks to customers."
  },
  {
    "id": "npc-a-helpful-fairy",
    "name": "A Helpful Fairy",
    "location": "Boss Lairs",
    "position": {
      "x": 133.22,
      "y": 123.158,
      "z": 15
    },
    "town": "Boss Lairs",
    "services": [],
    "description": "NPC"
  },
  {
    "id": "npc-a-lost-basher",
    "name": "A Lost Basher",
    "location": "[[The Spike]] 7 floors down.",
    "position": {
      "x": 125.172,
      "y": 127.118,
      "z": 14
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Lost Basher]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-lost-husher",
    "name": "A Lost Husher",
    "location": "[[The Spike]] 8 floors down.",
    "position": {
      "x": 125.211,
      "y": 127.2,
      "z": 15
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Lost Husher]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-lost-soul",
    "name": "A Lost Soul",
    "location": "[[Ghostlands]], two floors up",
    "position": {
      "x": 125.211,
      "y": 124.182,
      "z": 14
    },
    "town": "Carlin",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "This [[NPC]] is an unreachable illusion. It is actually located two floors above ground level, and when you approach it, it disappears (similar to the mirage in the desert near [[Darashia]])."
  },
  {
    "id": "npc-a-lost-thrower",
    "name": "A Lost Thrower",
    "location": "[[The Spike]] 7 floors down.",
    "position": {
      "x": 126.54,
      "y": 127.33,
      "z": 14
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Lost Thrower]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-majestic-warwolf",
    "name": "A Majestic Warwolf",
    "location": "[[Cormaya]], in a cave on the east part of the island",
    "position": {
      "x": 130.73,
      "y": 124.248,
      "z": 8
    },
    "town": "Edron",
    "services": [],
    "description": "Artist",
    "notes": "She will only talk to you if you are able to speak the language of wolves, otherwise she will only say GRRRRRRRRRRRRR. Her real name is '''Faolan''', as said by [[Ceiron]] who refers to her as the Great Wolf Mother.\n<br />\n\nThe language of wolves can be learnt from [[Ceiron]]. <br>\nShe is the NPC for the last step of the [[Druid Outfits Quest]]. She will grant you the final reward of the [[Druid Outfits Quest]]."
  },
  {
    "id": "npc-a-nightmare-scion",
    "name": "A Nightmare Scion",
    "location": "[[The Spike]] 6 floors down.",
    "position": {
      "x": 126.84,
      "y": 127.19,
      "z": 13
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Nightmare Scion]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-prisoner",
    "name": "A Prisoner",
    "location": "[[Mintwallin]] Prison",
    "position": {
      "x": 126.137,
      "y": 125.137,
      "z": 13
    },
    "town": "Thais",
    "services": [
      {
        "name": "Trade",
        "type": "other",
        "notes": "Buys/Sells (details not parsed yet)"
      }
    ],
    "description": "Sorcerer",
    "notes": "The prisoner is also known as the '''Mad Mage'''. Before becoming a prisoner he lived elsewhere in the cave system in the so-called [[Mad Mage Room]].<br>He was locked up in a tower in the [[Mintwallin]] prison because [[Markwin]] could not understand him. There is a note about him writen by Markwin in [[Chronicle of Mintwallin IV (Book)|one of his books]]. You will need [[Key 3620]] to open the door to the prison he is held in.<br>Say ''sell rune'' to him and he will offer you 50,000 gps for any blank rune you might have on you. However, he will only pay you 10 gps once you go through with the trade.Main [[NPC]] of the [[Mad Mage Room Quest]] and part of [[The Paradox Tower Quest]]."
  },
  {
    "id": "npc-a-restless-soul",
    "name": "A Restless Soul",
    "location": "[[Formorgar Mines]], second floor",
    "position": {
      "x": 126.1,
      "y": 121.125,
      "z": 10
    },
    "town": "Svargrond",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "In life he was known as Tylaf, an apprentice of [[Hjaern]]. He was tortured to death by the [[Cult]]ists but his soul remains.<br />\n\nPart of [[The Ice Islands Quest]].<br />\nThe first time you visit it you can't speak to it so just take the paper and go back to the shaman, after being granted the power to speak you must say: '''story''' to it in order to proceed."
  },
  {
    "id": "npc-a-runaway-goblin",
    "name": "A Runaway Goblin",
    "location": "Down a [[Pitfall]] in the west of [[Krailos]].",
    "position": {
      "x": 130.243,
      "y": 123.181,
      "z": 8
    },
    "town": "Krailos",
    "services": [],
    "description": "Merchant",
    "notes": "He refuses to tell you his name, as he is wanted by the [[Ogres]].Part of the [[Krailos Quest]]."
  },
  {
    "id": "npc-a-skull",
    "name": "A Skull",
    "location": "[[Hyaena Lairs]].",
    "position": {
      "x": 129.141,
      "y": 126.236,
      "z": 11
    },
    "town": "Darashia",
    "services": [],
    "description": "Undead",
    "notes": "There are two NPCs with this name next to each other.\n\nPart of {{Spoiler Section|Grimvale Quest|An Ancient Feud}}."
  },
  {
    "id": "npc-a-sleeping-dragon",
    "name": "A Sleeping Dragon",
    "location": "Northern [[Zao]].",
    "position": {
      "x": 129.219,
      "y": 121.243,
      "z": 10
    },
    "town": "Farmine",
    "services": [],
    "description": "Servant",
    "notes": "It is a popular belief that this dragon is the fearful [[Garsharak]] due to its similarity to how Garsharak appears in the [http://static.tibia.com/images/library/genesis4.jpg official artwork] of the [[Genesis]].<br />\nPart of [[Wrath of the Emperor Quest]].\n\nSometimes [[A Sleeping Dragon's Head Effect]] appears on top of it:\n[[File:A Sleeping Dragon (Blinking).gif]]"
  },
  {
    "id": "npc-a-starving-dog",
    "name": "A Starving Dog",
    "location": "[[Svargrond]], 2 levels up, west of the [[Formorgar Glacier]].",
    "position": {
      "x": 125.119,
      "y": 121.118,
      "z": 5
    },
    "town": "Svargrond",
    "services": [],
    "description": "Working Animal",
    "notes": "This starving dog is lost from its friend and owner, [[Iskan]].\nPart of [[The Ice Islands Quest]]."
  },
  {
    "id": "npc-a-strange-chalice",
    "name": "A Strange Chalice",
    "location": "[[Zao]]",
    "position": {
      "x": 130.139,
      "y": 121.149,
      "z": 9
    },
    "town": "Farmine",
    "services": [],
    "description": "Scientist",
    "notes": "Part of the [[Forgotten Knowledge Quest]]."
  },
  {
    "id": "npc-a-strange-fellow",
    "name": "A Strange Fellow",
    "location": "[[Venore]], below [[Depot]]",
    "position": {
      "x": 128.142,
      "y": 125.77,
      "z": 9
    },
    "town": "Venore",
    "services": [],
    "description": "Artist",
    "notes": "He has bought a fancy [[Magician Hat]] but not paid for it. His real name is David Brassacres.<br />\nYou are asked to find him in the [[Postman Quest]] to give him a bill."
  },
  {
    "id": "npc-a-swan",
    "name": "A Swan",
    "location": "[[Edron]], {{Mapper Coords|129.163|123.245|7|2|text=here}}.",
    "position": {
      "x": 129.161,
      "y": 123.245,
      "z": 7
    },
    "town": "Edron",
    "services": [],
    "description": "Guard",
    "notes": "Unlike [[Alkestios]] and [[Ikassis]], she did not take over the body of an animal when she travelled to the human realm. She is instead a swanmaiden, a type of Fae who can take on the appearance both of a swan and a young woman.Part of the [[Threatened Dreams Quest]]."
  },
  {
    "id": "npc-a-sweaty-cyclops",
    "name": "A Sweaty Cyclops",
    "location": "[[Ab'Dendriel]], on the fourth floor of a tower past a small [[Rotworm]] cave located below the [[Wheat Field]] east of depot in [[Underwood]]",
    "position": {
      "x": 127.185,
      "y": 123.186,
      "z": 3
    },
    "town": "Ab'Dendriel",
    "services": [
      {
        "name": "Trade",
        "type": "other",
        "notes": "Buys/Sells (details not parsed yet)"
      }
    ],
    "description": "Artisan",
    "notes": "A Sweaty Cyclops is [[Ab'Dendriel]]'s armorer. He lives in a tower north-east of the depot. His parents lived there before [[elves]] settled down there.\n\nAmong [[Cyclopes]] he is known as ''Bencthyclthrtrprr''. Humans call him ''Big Ben''.\n\nYou can reach him through an underground cave and ask him to trade certain weapons; however, he will not accept these items saying that they are not what he is looking for.\n\nHe is a smith, so he knows a lot about steel and its kinds: Mesh Kaha Rogh, Za'Kalortith, Uth'Byth, Uth'Morc, Uth'Amon, Uth'Lokr, Uth'Maer, Uth'Doon and Zatragil. You can have him forge certain rare metals from common items, but only by providing the appropriate language.\n\nLooks the same as a [[Cyclops]].\n\nTo have him forge metals, you need to do [[The Sweaty Cyclops Quest]].<br />He is a part of the [[Koshei The Deathless Quest]], [[The Hidden City of Beregar Quest]] and the [[Obsidian Knife Quest]]."
  },
  {
    "id": "npc-a-taffy-bunny",
    "name": "A Taffy Bunny",
    "location": "In the [[Dessert Dungeons]].",
    "position": {
      "x": 130.134,
      "y": 125.189,
      "z": 8
    },
    "town": "Feyrist",
    "services": [],
    "description": "NPC",
    "notes": "Part of the [[Threatened Dreams Quest#Sweet Dreams|Threatened Dreams Quest - Sweet Dreams]]."
  },
  {
    "id": "npc-a-tainted-soul",
    "name": "A Tainted Soul",
    "location": "[[Ghostlands]], two floors up",
    "position": {
      "x": 125.211,
      "y": 124.182,
      "z": 14
    },
    "town": "Carlin",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "This [[NPC]] is an unreachable illusion. It is actually located two floors above ground level, and when you approach it, it disappears (similar to the mirage in the desert near [[Darashia]])."
  },
  {
    "id": "npc-a-tortured-soul",
    "name": "A Tortured Soul",
    "location": "[[Ghostlands]], two floors up",
    "position": {
      "x": 125.211,
      "y": 124.182,
      "z": 14
    },
    "town": "Carlin",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "This [[NPC]] is an unreachable illusion. It is actually located two floors above ground level, and when you approach it, it disappears (similar to the mirage in the desert near [[Darashia]])."
  },
  {
    "id": "npc-a-vision-of-the-past",
    "name": "A Vision of the Past",
    "location": "[[Azzilon Castle]]",
    "position": {
      "x": 133.15,
      "y": 126.117,
      "z": 14
    },
    "town": "Edron",
    "services": [],
    "description": "NPC",
    "notes": "Part of the [[No Rest for the Wicked Quest]]."
  },
  {
    "id": "npc-a-vulcongra",
    "name": "A Vulcongra",
    "location": "[[The Spike]] 6 floors down.",
    "position": {
      "x": 125.129,
      "y": 127.47,
      "z": 13
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Vulcongra]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-a-wandering-soul",
    "name": "A Wandering Soul",
    "location": "North-western [[Vengoth]]",
    "position": {
      "x": 128.147,
      "y": 123.2,
      "z": 7
    },
    "town": "Farmine",
    "services": [],
    "description": "Unknown Occupation",
    "notes": "He is grieving the loss of a beloved one.<br>\nHe will help you enchant your [[Blood Crystal]] in the [[Blood Brothers Quest]]."
  },
  {
    "id": "npc-a-wrinkled-bonelord",
    "name": "A Wrinkled Bonelord",
    "location": "[[Hellgate Library]], under [[Ab'Dendriel]].",
    "position": {
      "x": 128.2,
      "y": 123.202,
      "z": 13
    },
    "town": "Ab'Dendriel",
    "services": [],
    "description": "Librarian",
    "notes": "He will burn you if you call him \"Blinky\"."
  },
  {
    "id": "npc-a-wyrm",
    "name": "A Wyrm",
    "location": "[[The Spike]] 8 floors down.",
    "position": {
      "x": 125.174,
      "y": 127.87,
      "z": 15
    },
    "town": "Venore",
    "services": [],
    "description": "Spy",
    "notes": "It's actually a [[Gnome]] posing as a [[Wyrm]].<br />\nPart of the [[Spike Tasks Quest]]."
  },
  {
    "id": "npc-abran-ironeye",
    "name": "Abran Ironeye",
    "location": "Near the south-west gate of [[Venore]], at the [[Ironhouse]].",
    "position": {
      "x": 128.139,
      "y": 125.116,
      "z": 5
    },
    "town": "Venore",
    "services": [],
    "description": "Shopmaster",
    "notes": "Abran is a warrior who runs the [[Ironhouse]], where he and his employees forge, repair and sell weapons and armors. Be careful asking him about ironeyes and [[Teddy Bear|teddy bears]].\nAbran Ironeye would like to see true warrior-king in Thais. Independence of Carlin is a proof for the weakness of Thais. He prays to [[Banor]]."
  }
];
